window.TRIP_SPOTS = [
  {
    id: "takamatsu-airport",
    name: "高松機場",
    category: "transport",
    categoryLabel: "交通",
    day: "D1/D6",
    date: "7/18・7/23",
    area: "高松機場",
    lat: 34.2142,
    lng: 134.0156,
    priority: "fixed",
    nav: "高松空港",
    note: "抵達、取車、還車與返台報到核心點。",
    tags: ["航班", "租車", "還車"]
  },
  {
    id: "route-inn-yashima",
    name: "Hotel Route Inn Takamatsu Yashima",
    category: "hotel",
    categoryLabel: "住宿",
    day: "D1-D4",
    date: "7/18-7/21",
    area: "高松屋島",
    lat: 34.3378,
    lng: 134.0978,
    priority: "fixed",
    nav: "ホテルルートイン高松屋島",
    note: "高松三晚住宿，D1-D3 每天回到這裡。",
    tags: ["住宿", "停車", "高松基地"]
  },
  {
    id: "dogo-haruka",
    name: "Kowakuen Haruka",
    category: "hotel",
    categoryLabel: "住宿",
    day: "D4-D6",
    date: "7/21-7/23",
    area: "道後",
    lat: 33.8509,
    lng: 132.7861,
    priority: "fixed",
    nav: "道後温泉 ホテル古湧園 遥",
    note: "道後兩晚住宿，晚上以步行逛道後溫泉街為主。",
    tags: ["住宿", "道後", "溫泉"]
  },
  {
    id: "donki-yashima",
    name: "唐吉訶德屋島店",
    category: "shopping",
    categoryLabel: "購物",
    day: "D1/D2/D3",
    date: "高松停留期間",
    area: "屋島",
    lat: 34.3412,
    lng: 134.1024,
    priority: "backup",
    nav: "ドン・キホーテ屋島店",
    note: "住宿附近的晚間補給點，適合零食、藥妝、飲料與旅途小物。",
    tags: ["晚間", "藥妝", "零食"]
  },
  {
    id: "ikkaku-takamatsu",
    name: "骨付鳥 一鶴 高松店",
    category: "food",
    categoryLabel: "美食",
    day: "D1/D3",
    date: "高松晚餐備案",
    area: "高松市區",
    lat: 34.3438,
    lng: 134.0518,
    priority: "backup",
    nav: "骨付鳥 一鶴 高松店",
    note: "香川名物骨付鳥，適合抵達日或高松市區日晚餐。",
    tags: ["香川名物", "晚餐", "可能排隊"]
  },
  {
    id: "waraya-udon",
    name: "讚岐うどん わら家",
    category: "food",
    categoryLabel: "美食",
    day: "D3",
    date: "7/20",
    area: "屋島",
    lat: 34.3393,
    lng: 134.1043,
    priority: "backup",
    nav: "讃岐うどん わら家",
    note: "屋島附近代表性烏龍麵店，可接四國村或屋島行程。",
    tags: ["讚岐烏龍麵", "屋島", "午餐"]
  },
  {
    id: "uzunomichi",
    name: "大鳴門橋遊步道・渦之道",
    category: "sightseeing",
    categoryLabel: "景點",
    day: "D2",
    date: "7/19",
    area: "鳴門",
    lat: 34.2403,
    lng: 134.6515,
    priority: "main",
    nav: "大鳴門橋遊歩道 渦の道",
    note: "D2 核心景點，出發前依潮汐調整抵達時間。",
    tags: ["鳴門", "潮汐", "海峽"]
  },
  {
    id: "narutoyama-observatory",
    name: "鳴門山展望台",
    category: "sightseeing",
    categoryLabel: "景點",
    day: "D2",
    date: "7/19",
    area: "鳴門",
    lat: 34.2383,
    lng: 134.6501,
    priority: "main",
    nav: "鳴門山展望台",
    note: "與渦之道同區域，適合看大鳴門橋與海峽全景。",
    tags: ["展望", "同區域", "短程散步"]
  },
  {
    id: "naruto-park-souvenir",
    name: "鳴門公園伴手禮",
    category: "souvenir",
    categoryLabel: "伴手禮",
    day: "D2",
    date: "7/19",
    area: "鳴門",
    lat: 34.2389,
    lng: 134.6492,
    priority: "backup",
    nav: "鳴門公園 お土産",
    note: "可買鳴門金時、鳴門わかめ與德島海味零食。",
    tags: ["德島", "鳴門金時", "伴手禮"]
  },
  {
    id: "workman-takamatsu-sogawa",
    name: "WORKMAN Plus 高松十川東店",
    category: "shopping",
    categoryLabel: "購物",
    day: "D2",
    date: "7/19",
    area: "高松東側",
    lat: 34.2875,
    lng: 134.1142,
    priority: "main",
    nav: "WORKMAN Plus 高松十川東店",
    note: "鳴門回程優先購物點，適合防曬、雨具、機能服與鞋襪。",
    tags: ["WORKMAN", "機能服", "停車"]
  },
  {
    id: "yamada-takamatsu-kasuga",
    name: "Yamada Denki 高松春日本店",
    category: "shopping",
    categoryLabel: "購物",
    day: "D2/D3",
    date: "高松備案",
    area: "高松春日",
    lat: 34.3317,
    lng: 134.0967,
    priority: "backup",
    nav: "Tecc LIFE SELECT 高松春日本店",
    note: "大型家電與免稅替代點，住宿附近可彈性安排。",
    tags: ["家電", "免稅", "備案"]
  },
  {
    id: "ritsurin-garden",
    name: "栗林公園",
    category: "sightseeing",
    categoryLabel: "景點",
    day: "D3",
    date: "7/20",
    area: "高松市區",
    lat: 34.3296,
    lng: 134.0439,
    priority: "main",
    nav: "栗林公園",
    note: "D3 早上主景點，高松代表庭園，避開正午暑熱。",
    tags: ["庭園", "早上優先", "高松"]
  },
  {
    id: "tamamo-park",
    name: "高松城跡・玉藻公園",
    category: "sightseeing",
    categoryLabel: "景點",
    day: "D3",
    date: "7/20",
    area: "高松港區",
    lat: 34.3505,
    lng: 134.0514,
    priority: "main",
    nav: "高松城跡 玉藻公園",
    note: "海城遺跡與庭園短程散步，接高松港與商店街很順。",
    tags: ["海城", "短程散步", "高松港"]
  },
  {
    id: "takamatsu-shotengai",
    name: "高松中央商店街",
    category: "shopping",
    categoryLabel: "商店街",
    day: "D3",
    date: "7/20",
    area: "高松市區",
    lat: 34.3428,
    lng: 134.0501,
    priority: "main",
    nav: "高松中央商店街",
    note: "午餐、逛街、避暑用，丸龜町與片原町一帶可彈性走。",
    tags: ["午餐", "商店街", "避暑"]
  },
  {
    id: "takamatsu-symbol-tower",
    name: "高松 Symbol Tower・港區展望",
    category: "sightseeing",
    categoryLabel: "展望",
    day: "D3",
    date: "7/20",
    area: "Sunport 高松",
    lat: 34.3526,
    lng: 134.0465,
    priority: "backup",
    nav: "高松シンボルタワー",
    note: "視天候短停，從港區看市區與瀨戶內海方向。",
    tags: ["展望", "港區", "可省略"]
  },
  {
    id: "shikoku-mura",
    name: "四國村 / Shikoku Mura",
    category: "backup",
    categoryLabel: "備案",
    day: "D3",
    date: "7/20",
    area: "屋島",
    lat: 34.3387,
    lng: 134.1045,
    priority: "backup",
    nav: "四国村ミウゼアム",
    note: "屋島附近戶外民家建築園區，若想增加文化點可替換部分市區時間。",
    tags: ["屋島", "文化", "戶外"]
  },
  {
    id: "yashimaji",
    name: "屋島寺",
    category: "sightseeing",
    categoryLabel: "景點",
    day: "D3",
    date: "7/20",
    area: "屋島山上",
    lat: 34.3565,
    lng: 134.1028,
    priority: "main",
    nav: "屋島寺",
    note: "屋島山上參拜點，可與獅子靈巖展望台一起走。",
    tags: ["屋島", "寺院", "山上"]
  },
  {
    id: "shishi-reigan",
    name: "屋島・獅子靈巖展望台",
    category: "sightseeing",
    categoryLabel: "展望",
    day: "D3",
    date: "7/20",
    area: "屋島山上",
    lat: 34.3596,
    lng: 134.1014,
    priority: "main",
    nav: "獅子の霊巌展望台",
    note: "D3 傍晚主景點，看瀨戶內海與高松市區景色。",
    tags: ["屋島", "展望", "傍晚"]
  },
  {
    id: "aeon-mall-takamatsu",
    name: "AEON Mall 高松",
    category: "shopping",
    categoryLabel: "購物",
    day: "D3",
    date: "7/20 晚間備案",
    area: "高松西側",
    lat: 34.3523,
    lng: 134.0056,
    priority: "main",
    nav: "イオンモール高松",
    note: "mont-bell 高松店與 Snow Peak 取扱店同棟，最適合整合戶外用品購物。",
    tags: ["停車", "商場", "戶外用品"]
  },
  {
    id: "montbell-takamatsu",
    name: "mont-bell 高松店",
    category: "outdoor",
    categoryLabel: "戶外用品",
    day: "D3",
    date: "7/20 晚間備案",
    area: "AEON Mall 高松 1F",
    lat: 34.3523,
    lng: 134.0056,
    priority: "main",
    nav: "モンベル 高松店",
    note: "大型店、Outlet 併設、免稅。這趟最建議加入的 mont-bell。",
    tags: ["mont-bell", "Outlet", "免稅"]
  },
  {
    id: "snowpeak-megasports-takamatsu",
    name: "Snow Peak 取扱：メガスポーツ高松店",
    category: "outdoor",
    categoryLabel: "戶外用品",
    day: "D3",
    date: "7/20 晚間備案",
    area: "AEON Mall 高松 2F",
    lat: 34.3523,
    lng: 134.0056,
    priority: "main",
    nav: "メガスポーツ 高松店 イオンモール高松",
    note: "Snow Peak 取扱店，和 mont-bell 同棟可一起逛。",
    tags: ["Snow Peak", "Gear", "同棟"]
  },
  {
    id: "zentsuji",
    name: "總本山善通寺",
    category: "sightseeing",
    categoryLabel: "景點",
    day: "D4",
    date: "7/21",
    area: "善通寺",
    lat: 34.2265,
    lng: 133.7774,
    priority: "main",
    nav: "総本山善通寺",
    note: "D4 香川文化線第一站，建議停留 45-60 分鐘。",
    tags: ["寺院", "四國遍路", "文化"]
  },
  {
    id: "kamado-souhonten",
    name: "名物かまど 總本店／周邊店",
    category: "souvenir",
    categoryLabel: "伴手禮",
    day: "D4",
    date: "7/21",
    area: "香川中西部",
    lat: 34.3193,
    lng: 133.8562,
    priority: "backup",
    nav: "名物かまど 総本店",
    note: "香川經典和菓子伴手禮，若路線順可短停。",
    tags: ["香川", "和菓子", "伴手禮"]
  },
  {
    id: "kotohiragu",
    name: "琴平・金刀比羅宮",
    category: "sightseeing",
    categoryLabel: "景點",
    day: "D4",
    date: "7/21",
    area: "琴平",
    lat: 34.1844,
    lng: 133.8092,
    priority: "main",
    nav: "金刀比羅宮",
    note: "D4 核心景點，階梯多，夏季依體力決定攀登高度。",
    tags: ["琴平", "785階", "夏季補水"]
  },
  {
    id: "kotohira-omotesando",
    name: "琴平表參道午餐",
    category: "food",
    categoryLabel: "美食",
    day: "D4",
    date: "7/21",
    area: "琴平",
    lat: 34.1901,
    lng: 133.8184,
    priority: "main",
    nav: "琴平 表参道 うどん",
    note: "金刀比羅宮前後最順的午餐區，依停車位置挑近的店。",
    tags: ["午餐", "烏龍麵", "表參道"]
  },
  {
    id: "kamitsubaki",
    name: "神椿",
    category: "food",
    categoryLabel: "休息",
    day: "D4",
    date: "7/21",
    area: "琴平",
    lat: 34.1853,
    lng: 133.8108,
    priority: "backup",
    nav: "神椿 琴平",
    note: "金刀比羅宮參道上的咖啡甜點休息點，適合補水與降溫。",
    tags: ["咖啡", "甜點", "休息"]
  },
  {
    id: "kyuman-ishidanya",
    name: "灸まん本舗 石段や",
    category: "souvenir",
    categoryLabel: "伴手禮",
    day: "D4",
    date: "7/21",
    area: "琴平",
    lat: 34.1887,
    lng: 133.8180,
    priority: "backup",
    nav: "灸まん本舗 石段や",
    note: "琴平代表性甜點，適合當作在地伴手禮。",
    tags: ["琴平", "甜點", "伴手禮"]
  },
  {
    id: "marugame-castle",
    name: "丸龜城",
    category: "sightseeing",
    categoryLabel: "景點",
    day: "D4",
    date: "7/21",
    area: "丸龜",
    lat: 34.2861,
    lng: 133.8002,
    priority: "main",
    nav: "丸亀城",
    note: "以天守與石垣為主，時間不足可外觀拍照。",
    tags: ["城郭", "石垣", "短停"]
  },
  {
    id: "ikkaku-marugame",
    name: "骨付鳥 一鶴 丸龜本店",
    category: "food",
    categoryLabel: "美食",
    day: "D4",
    date: "7/21",
    area: "丸龜",
    lat: 34.2890,
    lng: 133.7950,
    priority: "backup",
    nav: "骨付鳥 一鶴 丸亀本店",
    note: "香川骨付鳥名店，時間夠再加，不要壓縮道後入住。",
    tags: ["骨付鳥", "丸龜", "時間夠再去"]
  },
  {
    id: "donki-marugame",
    name: "唐吉訶德丸龜店",
    category: "shopping",
    categoryLabel: "購物",
    day: "D4",
    date: "7/21 備案",
    area: "丸龜",
    lat: 34.2700,
    lng: 133.7930,
    priority: "backup",
    nav: "ドン・キホーテ丸亀店",
    note: "只有景點提早完成才加，避免延誤前往松山。",
    tags: ["備案", "藥妝", "零食"]
  },
  {
    id: "snowpeak-utazu",
    name: "Snow Peak Store Alpen Outdoors 宇多津店",
    category: "outdoor",
    categoryLabel: "戶外用品",
    day: "D4",
    date: "7/21 備案",
    area: "宇多津",
    lat: 34.3106,
    lng: 133.8121,
    priority: "backup",
    nav: "Snow Peak Store アルペンアウトドアーズ 宇多津店",
    note: "比較完整的 Snow Peak Store，但會壓縮 D4 往道後時間。",
    tags: ["Snow Peak", "宇多津", "時間夠再去"]
  },
  {
    id: "matsuyama-castle-ropeway",
    name: "松山城・纜車街",
    category: "sightseeing",
    categoryLabel: "景點",
    day: "D5",
    date: "7/22",
    area: "松山市區",
    lat: 33.8434,
    lng: 132.7693,
    priority: "main",
    nav: "松山城ロープウェイのりば東雲口",
    note: "D5 上午主景點，先登城避開暑熱。",
    tags: ["松山城", "上午", "纜車"]
  },
  {
    id: "goshiki",
    name: "鄉土料理 五志喜",
    category: "food",
    categoryLabel: "美食",
    day: "D5",
    date: "7/22",
    area: "松山市區",
    lat: 33.8380,
    lng: 132.7658,
    priority: "backup",
    nav: "郷土料理 五志喜 松山",
    note: "想吃鯛飯、五色素麵等愛媛鄉土料理時可列入午餐或晚餐。",
    tags: ["愛媛料理", "鯛飯", "午餐"]
  },
  {
    id: "kadoya-okaido",
    name: "かどや 大街道店",
    category: "food",
    categoryLabel: "美食",
    day: "D5",
    date: "7/22",
    area: "大街道",
    lat: 33.8397,
    lng: 132.7700,
    priority: "backup",
    nav: "かどや 大街道店",
    note: "宇和島鯛めし與愛媛料理，位置適合接大街道逛街。",
    tags: ["鯛めし", "大街道", "愛媛"]
  },
  {
    id: "donki-okaido",
    name: "唐吉訶德松山大街道店",
    category: "shopping",
    categoryLabel: "購物",
    day: "D5",
    date: "7/22",
    area: "大街道",
    lat: 33.8396,
    lng: 132.7698,
    priority: "main",
    nav: "ドン・キホーテ松山大街道店",
    note: "排在大街道步行動線中，買零食、藥妝、日用品方便。",
    tags: ["大街道", "藥妝", "步行"]
  },
  {
    id: "okaido-gintengai",
    name: "大街道・銀天街",
    category: "shopping",
    categoryLabel: "商店街",
    day: "D5",
    date: "7/22",
    area: "松山市區",
    lat: 33.8381,
    lng: 132.7668,
    priority: "main",
    nav: "松山 大街道 銀天街",
    note: "松山市中心主要商店街，雨天也好走。",
    tags: ["逛街", "雨天備案", "咖啡"]
  },
  {
    id: "montbell-matsuyama",
    name: "mont-bell 松山店",
    category: "outdoor",
    categoryLabel: "戶外用品",
    day: "D5",
    date: "7/22 備案",
    area: "松山市",
    lat: 33.8228,
    lng: 132.7478,
    priority: "backup",
    nav: "モンベル 松山店",
    note: "松山也有 mont-bell，若高松沒逛到可作備案。",
    tags: ["mont-bell", "免稅", "備案"]
  },
  {
    id: "snowpeak-kompas-matsuyama",
    name: "Snow Peak 取扱：アウトドアーズ・コンパス",
    category: "outdoor",
    categoryLabel: "戶外用品",
    day: "D5",
    date: "7/22 備案",
    area: "松山市山越",
    lat: 33.8606,
    lng: 132.7625,
    priority: "backup",
    nav: "アウトドアーズ・コンパス 松山 山越",
    note: "松山市 Snow Peak 取扱店，若想看戶外用品可加。",
    tags: ["Snow Peak", "松山", "備案"]
  },
  {
    id: "dogo-onsen-honkan",
    name: "道後溫泉本館",
    category: "sightseeing",
    categoryLabel: "溫泉",
    day: "D5",
    date: "7/22",
    area: "道後",
    lat: 33.8520,
    lng: 132.7865,
    priority: "main",
    nav: "道後温泉本館",
    note: "道後代表景點，從飯店步行安排泡湯與夜間散步。",
    tags: ["溫泉", "步行", "夜間"]
  },
  {
    id: "dogo-haikara",
    name: "道後ハイカラ通り",
    category: "souvenir",
    categoryLabel: "伴手禮",
    day: "D5",
    date: "7/22",
    area: "道後",
    lat: 33.8518,
    lng: 132.7859,
    priority: "main",
    nav: "道後ハイカラ通り",
    note: "道後溫泉商店街，買一六タルト、坊っちゃん団子、蜜柑果凍與今治毛巾。",
    tags: ["道後", "伴手禮", "步行"]
  },
  {
    id: "ichiroku-dogo",
    name: "一六本舗 道後店",
    category: "souvenir",
    categoryLabel: "伴手禮",
    day: "D5",
    date: "7/22",
    area: "道後",
    lat: 33.8512,
    lng: 132.7856,
    priority: "main",
    nav: "一六本舗 道後店",
    note: "一六タルト是愛媛代表伴手禮，住道後時步行買最順。",
    tags: ["一六タルト", "愛媛", "伴手禮"]
  },
  {
    id: "dogo-beer",
    name: "道後麥酒館",
    category: "food",
    categoryLabel: "美食",
    day: "D5",
    date: "7/22",
    area: "道後",
    lat: 33.8522,
    lng: 132.7862,
    priority: "backup",
    nav: "道後麦酒館",
    note: "泡湯前後的晚餐或飲料備案，不開車時比較適合。",
    tags: ["晚餐", "道後", "步行"]
  },
  {
    id: "workman-matsuyama-inter",
    name: "WORKMAN Plus 松山交流道店",
    category: "shopping",
    categoryLabel: "購物",
    day: "D6",
    date: "7/23",
    area: "松山交流道",
    lat: 33.7895,
    lng: 132.7944,
    priority: "backup",
    nav: "WORKMAN Plus 松山インター店",
    note: "最後補買機能服、雨具、鞋襪，逛完直接上高速。",
    tags: ["WORKMAN", "交流道", "最後補買"]
  },
  {
    id: "montbell-ishizuchi-oasis",
    name: "mont-bell アウトドアオアシス石鎚店",
    category: "outdoor",
    categoryLabel: "戶外用品",
    day: "D6",
    date: "7/23 備案",
    area: "石鎚山 SA / 小松オアシス",
    lat: 33.8932,
    lng: 133.1160,
    priority: "backup",
    nav: "モンベル アウトドアオアシス石鎚店",
    note: "松山回高松高速路線上的 mont-bell 備案，時間夠才停。",
    tags: ["mont-bell", "高速路線", "備案"]
  },
  {
    id: "ishizuchiyama-sa",
    name: "石鎚山 SA",
    category: "souvenir",
    categoryLabel: "休息站",
    day: "D6",
    date: "7/23",
    area: "松山道",
    lat: 33.8936,
    lng: 133.1166,
    priority: "backup",
    nav: "石鎚山サービスエリア",
    note: "高速休息、上廁所與補買四國零食。",
    tags: ["高速", "休息", "伴手禮"]
  },
  {
    id: "toyohama-sa",
    name: "豐浜 SA",
    category: "souvenir",
    categoryLabel: "休息站",
    day: "D6",
    date: "7/23",
    area: "高松道",
    lat: 34.0576,
    lng: 133.6275,
    priority: "backup",
    nav: "豊浜サービスエリア",
    note: "回高松途中休息與最後伴手禮補買。",
    tags: ["高速", "休息", "伴手禮"]
  },
  {
    id: "takamatsu-airport-souvenir",
    name: "高松機場伴手禮",
    category: "souvenir",
    categoryLabel: "伴手禮",
    day: "D6",
    date: "7/23",
    area: "高松機場",
    lat: 34.2142,
    lng: 134.0156,
    priority: "backup",
    nav: "高松空港 お土産",
    note: "最後保險點：讚岐烏龍麵、和三盆、香川零食。",
    tags: ["機場", "最後採買", "香川"]
  },
  {
    id: "unpenji-ropeway",
    name: "雲邊寺山頂公園・纜車",
    category: "backup",
    categoryLabel: "遠程備案",
    day: "備案",
    date: "西香川線",
    area: "觀音寺",
    lat: 34.0766,
    lng: 133.7204,
    priority: "optional",
    nav: "雲辺寺ロープウェイ 山麓駅",
    note: "景色強但距離遠，較適合替換成西香川攝影線，不建議塞入高松日。",
    tags: ["西香川", "纜車", "遠程"]
  },
  {
    id: "takaya-shrine",
    name: "天空鳥居 高屋神社",
    category: "backup",
    categoryLabel: "遠程備案",
    day: "備案",
    date: "西香川線",
    area: "觀音寺",
    lat: 34.0777,
    lng: 133.6616,
    priority: "optional",
    nav: "高屋神社 天空の鳥居",
    note: "拍照很美，但假日可能有交通管制或接駁，需另排一條線。",
    tags: ["天空鳥居", "西香川", "交通管制"]
  },
  {
    id: "zenigata-sunae",
    name: "銭形沙畫",
    category: "backup",
    categoryLabel: "遠程備案",
    day: "備案",
    date: "西香川線",
    area: "觀音寺",
    lat: 34.1234,
    lng: 133.6527,
    priority: "optional",
    nav: "銭形砂絵 琴弾公園",
    note: "可與高屋神社、父母之濱串成西香川線。",
    tags: ["觀音寺", "沙畫", "遠程"]
  },
  {
    id: "chichibugahama",
    name: "父母之濱",
    category: "backup",
    categoryLabel: "遠程備案",
    day: "備案",
    date: "西香川線",
    area: "三豐",
    lat: 34.2106,
    lng: 133.6391,
    priority: "optional",
    nav: "父母ヶ浜",
    note: "夕陽與退潮時最美，但需要看潮汐，回高松會變晚。",
    tags: ["夕陽", "潮汐", "西香川"]
  },
  {
    id: "montbell-tokushima",
    name: "mont-bell 德島店",
    category: "outdoor",
    categoryLabel: "戶外用品",
    day: "D2 備案",
    date: "鳴門日不建議特地繞",
    area: "德島市",
    lat: 34.1170,
    lng: 134.5310,
    priority: "optional",
    nav: "モンベル 徳島店",
    note: "大型店但偏離鳴門主線，除非 D2 想大幅改成德島購物才去。",
    tags: ["mont-bell", "德島", "不特地繞"]
  },
  {
    id: "snowpeak-aizumi",
    name: "Snow Peak Store 德島藍住店",
    category: "outdoor",
    categoryLabel: "戶外用品",
    day: "D2 備案",
    date: "鳴門日不建議特地繞",
    area: "德島藍住",
    lat: 34.1260,
    lng: 134.5020,
    priority: "optional",
    nav: "Snow Peak Store アルペンアウトドアーズ エッセンシャルストア 徳島藍住店",
    note: "Snow Peak 取扱店，但與 D2 鳴門海峽主線不完全順。",
    tags: ["Snow Peak", "德島", "不特地繞"]
  }
];

window.TRIP_SPOT_META = {
  updatedAt: "2026-07-07 09:10",
  version: "nearby spots v1",
  note: "座標用於附近排序，實際導航以 Google Maps 查詢結果為準。"
};